pipeline:

  build:
    image: golang:latest
    pull: true
    commands:
    - go build
    - go test -v
    when:
      event: push

  publish:
    image: golang:latest
    environment:
    - GITHUB_TOKEN=${GITHUB_TOKEN}
    - GITHUB_REPO=gitenv
    - GITHUB_USER=ElementAI
    commands:
    - go get github.com/aktau/github-release
    - >-
      github-release release
      --tag ${DRONE_TAG}
      --name gitenv-${DRONE_TAG}
      --description "See ${DRONE_BUILD_LINK}"
    - GOOS=linux GOARCH=amd64 go build
    - tar czf gitenv.tar.gz gitenv
    - >-
      github-release upload
      --tag ${DRONE_TAG}
      --replace
      --label "Linux 64-bits"
      --name gitenv-linux-amd64.tar.gz
      --file gitenv.tar.gz
    - GOOS=darwin GOARCH=amd64 go build
    - tar czf gitenv.tar.gz gitenv
    - >-
      github-release upload
      --tag ${DRONE_TAG}
      --replace
      --label "MacOS 64-bits"
      --name gitenv-macos-amd64.tar.gz
      --file gitenv.tar.gz
    when:
      event: tag
