pipeline:

  build:
    image: golang
    pull: true
    commands:
    - go build
    - go test -v
    when:
      event: push

  publish:
    image: golang
    secrets: [ github_token ]
    environment:
    - GITHUB_REPO=gitenv
    - GITHUB_USER=ElementAI
    - DOCKER_IMAGE=images.borgy.elementai.lan/gitenv/gitenv
    commands:
    - go get github.com/aktau/github-release
    - >-
      github-release release
      --tag ${DRONE_TAG}
      --name gitenv-${DRONE_TAG}
      --description "See ${DRONE_BUILD_LINK}"
    - GOOS=darwin GOARCH=amd64 go build -o gitenv
    - tar czf gitenv.tar.gz gitenv
    - >-
      github-release upload
      --tag ${DRONE_TAG}
      --replace
      --label "MacOS 64-bits"
      --name gitenv-macos-amd64.tar.gz
      --file gitenv.tar.gz
    - GOOS=linux GOARCH=amd64 go build -o gitenv
    - tar czf gitenv.tar.gz gitenv
    - >-
      github-release upload
      --tag ${DRONE_TAG}
      --replace
      --label "Linux 64-bits"
      --name gitenv-linux-amd64.tar.gz
      --file gitenv.tar.gz
    when:
      event: tag

  docker:
    images: plugins/docker
    registry: images.borgy.elementai.lan
    repo: gitenv/gitenv
    when:
      event: tag
